# Generated by Django 2.2 on 2021-09-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iGame_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
