# Generated by Django 2.2 on 2021-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iGame_app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_games',
        ),
        migrations.AddField(
            model_name='game',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_games', to='iGame_app.User'),
        ),
    ]
