# Generated by Django 2.2 on 2021-09-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iGame_app', '0003_auto_20210914_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='favorited_by',
        ),
    ]
